var annotated =
[
    [ "AccelerometerInput", "class_accelerometer_input.html", null ],
    [ "AnimatedBillboard", "class_animated_billboard.html", "class_animated_billboard" ],
    [ "ApplicationExit", "class_application_exit.html", null ],
    [ "BlockRecycler", "class_block_recycler.html", null ],
    [ "BlockTransparency", "class_block_transparency.html", "class_block_transparency" ],
    [ "buttonColor", "classbutton_color.html", "classbutton_color" ],
    [ "DropBlock", "class_drop_block.html", null ],
    [ "DropBorders", "class_drop_borders.html", "class_drop_borders" ],
    [ "DropBordersHelper", "class_drop_borders_helper.html", "class_drop_borders_helper" ],
    [ "FinishTrigger", "class_finish_trigger.html", "class_finish_trigger" ],
    [ "FollowPlayer", "class_follow_player.html", "class_follow_player" ],
    [ "GameConfig", "class_game_config.html", "class_game_config" ],
    [ "GameConfigHelper", "class_game_config_helper.html", "class_game_config_helper" ],
    [ "goToMenu", "classgo_to_menu.html", null ],
    [ "HighScoreGUI", "class_high_score_g_u_i.html", "class_high_score_g_u_i" ],
    [ "InstantiateGame", "class_instantiate_game.html", "class_instantiate_game" ],
    [ "MenuScript", "class_menu_script.html", "class_menu_script" ],
    [ "PauseConditions", "class_pause_conditions.html", "class_pause_conditions" ],
    [ "PickupCoin", "class_pickup_coin.html", null ],
    [ "ResetPlayer", "class_reset_player.html", null ],
    [ "RotateGUI", "class_rotate_g_u_i.html", "class_rotate_g_u_i" ],
    [ "ScaleInGameGUI", "class_scale_in_game_g_u_i.html", "class_scale_in_game_g_u_i" ],
    [ "ScoreCounter", "class_score_counter.html", "class_score_counter" ],
    [ "SpawnPoint", "class_spawn_point.html", "class_spawn_point" ],
    [ "tutorialPressed", "classtutorial_pressed.html", null ],
    [ "UILevelSelect", "class_u_i_level_select.html", "class_u_i_level_select" ],
    [ "WaterTransparency", "class_water_transparency.html", "class_water_transparency" ],
    [ "WaterTrigger", "class_water_trigger.html", null ],
    [ "winNow", "classwin_now.html", null ],
    [ "WonScreen", "class_won_screen.html", "class_won_screen" ]
];